import type { ExchangeItem } from './types'

export const stableYieldExchanges: ExchangeItem[] = [
  {
    id: 'binance',
    name: 'Binance',
    slug: 'binance',
    referralUrl: 'https://www.binance.com/register?ref=C7MFGY6C',
    icon: '/images/crypto/exchanges/icons/binance.svg',
    logo: '/images/crypto/exchanges/logos/binance.svg',
    isActive: true,
  },
  {
    id: 'bybit',
    name: 'Bybit',
    slug: 'bybit',
    referralUrl: 'https://www.bybit.com/invite?ref=9A61MJ',
    icon: 'BB',
    logo: '/images/crypto/exchanges/logos/bybit.svg',
    isActive: true,
  },
  {
    id: 'mexc',
    name: 'MEXC',
    slug: 'mexc',
    referralUrl: 'https://promote.mexc.com/r/7Bd54sVtHR',
    icon: 'MX',
    logo: '/images/crypto/exchanges/logos/mexc.svg',
    isActive: true,
  },
  {
    id: 'bingx',
    name: 'BingX',
    slug: 'bingx',
    referralUrl: 'https://bingxdao.com/invite/YWRV6H/',
    icon: 'BX',
    logo: '/images/crypto/exchanges/logos/bingx.svg',
    isActive: true,
  },
  {
    id: 'okx',
    name: 'OKX',
    slug: 'okx',
    referralUrl: 'https://okx.com/join/99946948',
    icon: 'OK',
    logo: '/images/crypto/exchanges/logos/okx.svg',
    isActive: true,
  },
  {
    id: 'kucoin',
    name: 'KuCoin',
    slug: 'kucoin',
    referralUrl: 'https://www.kucoin.com/r/rf/CXEJSDHX',
    icon: 'KC',
    logo: '/images/crypto/exchanges/logos/kucoin.svg',
    isActive: true,
  },
  {
    id: 'gate',
    name: 'Gate',
    slug: 'gate',
    referralUrl: 'https://www.gate.com/signup/VFFFVAPZCA?ref_type=103',
    icon: 'GT',
    logo: '/images/crypto/exchanges/logos/gate.svg',
    isActive: true,
  },
  {
    id: 'bitget',
    name: 'Bitget',
    slug: 'bitget',
    referralUrl: 'https://share.bitget.com/u/7ZTDK6NJ',
    icon: 'BG',
    logo: '/images/crypto/exchanges/logos/bitget.svg',
    isActive: true,
  },
  {
    id: 'nexo',
    name: 'Nexo',
    slug: 'nexo',
    referralUrl: 'https://nexo.com/ref/rjgjfbbgrh?src=web-link',
    icon: 'NX',
    logo: '/images/crypto/exchanges/logos/nexo.svg',
    isActive: false,
  },
  {
    id: 'htx',
    name: 'HTX',
    slug: 'htx',
    referralUrl: 'https://www.htx.com/invite/en-us/1f?invite_code=afzbe223',
    icon: 'HT',
    logo: '/images/crypto/exchanges/logos/htx.svg',
    isActive: true,
  },
  {
    id: 'xt',
    name: 'XT',
    slug: 'xt',
    referralUrl: 'https://www.xt.com/ref/9FZTXG',
    icon: '/images/crypto/exchanges/icons/xt.svg',
    logo: '/images/crypto/exchanges/logos/xt.svg',
    isActive: true,
  },
  {
    id: 'whitebit',
    name: 'Whitebit',
    slug: 'whitebit',
    referralUrl:
      'https://whitebit.com/referral/9b39bc02-48e0-4345-b98f-46e0c6b3cb1f',
    icon: 'WB',
    logo: {
      light: '/images/crypto/exchanges/logos/whitebit-light.svg',
      dark: '/images/crypto/exchanges/logos/whitebit-dark.svg',
    },
    isActive: true,
  },
]
